### ISSUE TITLE
Watermark certificates

### ISSUE THREAD

**Issue by chriscz** [awalterschulze/waltercv#1]
To mitigate potential identity theft you may want to add some "deep" watermark over each PDF.

**Comment by awalterschulze** [comment]
How?

**Comment by chriscz** [comment]
https://github.com/chriscz/watermark

**Comment by awalterschulze** [comment]
Ok so we need to add imagemagic to the docker, if its not already there.
And then edit the build script by adding your extra commands.
Pretty cool.
Thanks.

**Comment by chriscz** [comment]
imagemagic and pdftk. 
If you'd like alternative watermarks they're pretty easy to generate using [GIMP's tiling feature](https://superuser.com/questions/384393/using-gimp-easiest-way-to-repeat-an-image-in-a-tiled-fashion)

I used 5% opacity for the light watermark and around 9% for the darker version. Text size was 130 or 140pt and page size A4.

**Comment by awalterschulze** [comment]
But even if I add the watermark, this all still in a script that anyone can
edit. So what did I really protect?

**Comment by chriscz** [comment]
Oh right you may have misunderstood me. In the original post I meant watermarking your degree certificates for honours, masters and bachelor's.

**Comment by awalterschulze** [comment]
Good point. That makes sense. But if I watermark them now then someone can
still find the originals in the git history.

**Comment by chriscz** [comment]
I assumed you'll rewrite your history ;P

**Comment by chriscz** [comment]
It might already be too late; but also not.

**Comment by awalterschulze** [comment]
Thats fair 😀

So just to make sure that this is worth the effort. Can someone really
steal my identity with only my degrees?

**Comment by chriscz** [comment]
I really don't know. But I'd rather you not find out :laughing:

**Comment by awalterschulze** [comment]
I think and hope they will need more than my degrees.
